version: "3"
networks: 
  docker-env:

services:
  php:
    container_name: dev-php-7
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
      - ./php7/:/var/www/html
    working_dir: /var/www/html
    restart: on-failure
    ports:
      - 7000:80
    depends_on:
      - db_maria

  php72:
    container_name: dev-php-72
    build:
      context: .
      dockerfile: .docker/php7-2/Dockerfile
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
      - ../program-web:/var/www/html
    working_dir: /var/www/html
    restart: on-failure
    ports:
      - 7200:80
      - 7280:8000
    depends_on:
      - db_maria
    networks: 
      - docker-env
  
  php73:
    container_name: dev-php-73
    build:
      context: .
      dockerfile: .docker/php7-3/Dockerfile
    volumes:
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
      - ../program-web:/var/www/html
    working_dir: /var/www/html
    restart: on-failure
    ports:
      - 7300:80
      - 7380:8000
    depends_on:
      - db_maria
    networks: 
      - docker-env

  php5:
    container_name: dev-php-5-5
    build:
      context: .
      dockerfile: .docker/php5/Dockerfile
    volumes:
      - ./.docker/php5/php.ini:/usr/local/etc/php/php.ini
      - ../program-web:/var/www/html
    working_dir: /var/www/html
    restart: on-failure
    ports:
      - 5500:80
    depends_on:
      - db_maria
    networks: 
      - docker-env

  php56:
    container_name: dev-php-5-6
    build:
      context: .
      dockerfile: .docker/php5-6-4-apache/Dockerfile
    volumes:
      - ./.docker/php5-6-4-apache/php.ini:/usr/local/etc/php/php.ini
      - ../program-web:/var/www/html
    working_dir: /var/www/html
    restart: on-failure
    ports:
      - 5600:80
    depends_on:
      - db_maria
    networks: 
      - docker-env
  
  nginxicoreapi:
    image: nginx:stable-alpine
    container_name: nginx-icore-api
    ports:
        - "5640:80"
    volumes: 
        - ../program-web/icore-api/src:/var/www/html
        - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
        - php53icoreapi
        - db_maria
    networks: 
        - docker-env

  php53icoreapi:
    build:
        context: .
        dockerfile: .docker/php5-6-4/Dockerfile
    container_name: php55-icore-api
    ports:
        - "9000:9000"
    volumes:
        - ../program-web/icore-api/src:/var/www/html
    networks:
        - docker-env

  db_maria:
    container_name: db-maria-dev
    image: mariadb
    ports:
      - 3303:3306
    volumes:
      - ../program-database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: icorelab
      MYSQL_USER: root
      MYSQL_PASSWORD: rahasia
      MYSQL_ROOT_PASSWORD: rahasia
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadbclp
    restart: unless-stopped
    networks: 
      - docker-env
