TYPE=VIEW
query=select `sr`.`id` AS `id`,`sr`.`member_id` AS `member_id`,`sr`.`name` AS `name`,`sr`.`email` AS `email`,`sr`.`phone` AS `phone`,`sr`.`company` AS `company`,`sr`.`position` AS `position`,`sr`.`company_phone` AS `company_phone`,`sr`.`company_fax` AS `company_fax`,`sr`.`company_address` AS `company_address`,`sr`.`company_city` AS `company_city`,`sr`.`company_zipcode` AS `company_zipcode`,`sr`.`training_category_id` AS `training_category_id`,`s`.`title` AS `title`,`sr`.`training_id` AS `training_id`,`sr`.`training_modules` AS `training_modules`,`sr`.`training_type` AS `training_type`,`sr`.`training_option` AS `training_option`,`sr`.`meeting_date` AS `meeting_date`,`sr`.`meeting_location` AS `meeting_location`,`sr`.`note` AS `note`,`sr`.`status` AS `status`,`sr`.`created_at` AS `created_at`,`sr`.`last_update` AS `last_update` from (`eximiuslearningweb`.`training_requests` `sr` left join `eximiuslearningweb`.`training_categories` `s` on(`s`.`id` = `sr`.`training_category_id`))
md5=8a089a65ce97bc27b314bfdee7aec3dc
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2020-07-09 09:38:37
create-version=2
source=select `sr`.`id` AS `id`,`sr`.`member_id` AS `member_id`,`sr`.`name` AS `name`,`sr`.`email` AS `email`,`sr`.`phone` AS `phone`,`sr`.`company` AS `company`,`sr`.`position` AS `position`,`sr`.`company_phone` AS `company_phone`,`sr`.`company_fax` AS `company_fax`,`sr`.`company_address` AS `company_address`,`sr`.`company_city` AS `company_city`,`sr`.`company_zipcode` AS `company_zipcode`,`sr`.`training_category_id` AS `training_category_id`,`s`.`title` AS `title`,`sr`.`training_id` AS `training_id`,`sr`.`training_modules` AS `training_modules`,`sr`.`training_type` AS `training_type`,`sr`.`training_option` AS `training_option`,`sr`.`meeting_date` AS `meeting_date`,`sr`.`meeting_location` AS `meeting_location`,`sr`.`note` AS `note`,`sr`.`status` AS `status`,`sr`.`created_at` AS `created_at`,`sr`.`last_update` AS `last_update` from (`training_requests` `sr` left join `training_categories` `s` on((`s`.`id` = `sr`.`training_category_id`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `sr`.`id` AS `id`,`sr`.`member_id` AS `member_id`,`sr`.`name` AS `name`,`sr`.`email` AS `email`,`sr`.`phone` AS `phone`,`sr`.`company` AS `company`,`sr`.`position` AS `position`,`sr`.`company_phone` AS `company_phone`,`sr`.`company_fax` AS `company_fax`,`sr`.`company_address` AS `company_address`,`sr`.`company_city` AS `company_city`,`sr`.`company_zipcode` AS `company_zipcode`,`sr`.`training_category_id` AS `training_category_id`,`s`.`title` AS `title`,`sr`.`training_id` AS `training_id`,`sr`.`training_modules` AS `training_modules`,`sr`.`training_type` AS `training_type`,`sr`.`training_option` AS `training_option`,`sr`.`meeting_date` AS `meeting_date`,`sr`.`meeting_location` AS `meeting_location`,`sr`.`note` AS `note`,`sr`.`status` AS `status`,`sr`.`created_at` AS `created_at`,`sr`.`last_update` AS `last_update` from (`eximiuslearningweb`.`training_requests` `sr` left join `eximiuslearningweb`.`training_categories` `s` on(`s`.`id` = `sr`.`training_category_id`))
mariadb-version=100504
